### ISSUE TITLE
Noise and Alert track+deck is frequently confusing

### ISSUE THREAD

**Issue by djrenren** [andymeneely/project-timber-wolf#6]
So when a noise is generated a player must
- Move up the noise track
- Count the number of alert spaces reached
- Discard that many cards

This flow makes it difficult to look ahead (which is the point of a deterministic event deck). It gets even more complex when actions cause alerts as well.

While not a perfect solution, it may work well to insert blank cards into the deck to represent the blank spots on the tracker board. This way, 1 noise = 1 card. Then looking ahead is simply adding the noise count to the number on the last card revealed.

Raising the alert level directly is tough because it corresponds to an undetermined amount of noise. And encourages trickery around the application of noise. Consider the following where o's are empty spaces on the track and x's are alerts:
```
o-o-o-x-o
```
If the team generates 4 noise and an alert, they should apply 3 noise, then the alert, then 1 noise. It turns out that beyond the beginning of the game, this behavior happens a lot.

As per the tracker here: https://github.com/andymeneely/project-timber-wolf/blob/master/maker/tracker.svg raising the alert only does much for the first 8-15 noise.

From an explanation standpoint, it's also difficult to explain to people that raising the alert doesn't actually cause anything to happen until the end of the turn.

## Strawman Proposals
- Add a "Hazard deck" you draw from instead of raising the alert. You would then do whatever is on the card immediately (and these could be shuffled or not)
- Replace "Raise Alert" with more noise

I know with board games the most useful feedback is how it went not suggestions but figured I'd throw them out there just in case.

**Comment by andymeneely** [comment]
Eh, I have to say that a *lot* of people have *not* found this to be confusing so I'm not sure there's a lot of confusion on this mechanic at the moment. 

Just to be clear - because I'm realizing that I did not prep a new release since my June work - the Event deck is face-up the whole time. 

We can't do 1 noise = 1 card because we need to be able to raise alerts directly. Also setting up the deck adds to the setup time.

The order in which you add up your noises during the action phase still can be done in any order, so it doesn't matter if you add up your noises at the beginning or end of the phase. For like six months we were playing where you add up your noises as you do your action until we came up with the convention that you just raise your fingers at the end.

I am confused by one part of your statement... raising an alert does not *cause* more noise. Noises cause Alerts. Alerts increase the severity of the Event. Events cause more Alerts.

One thing that we tend to do is to put two noise markers down, so you know how many you started and ended with, then dealing those cards off. Of course you can't completely undo everything if you're revealing stuff, but it works for most folks.

I definitely don't like the Hazard deck idea. That turns into concurrency problems because people are working simultaneously during that action phase for efficient teams. Plus it adds more randomness which I don't like.

**Comment by djrenren** [comment]
Fair enough, playtest data definitely trumps my opinion. And I see your point about the hazard deck.

To clarify the "Alerts cause noise":

When you make noise, you move up the noise track and reach points where you raise an alert.

I thought if you raise an alert due to an action or event card, you must move up the noise track to match it.  If I'm mistaken, and this is not the case, then the noise tracker will not actually track your progress to the alarm particularly well but it's definitely way easier to think about.

Having reread the rules (especially the ones in master) this seems to be the case, and I think we've been playing incorrectly

**Comment by andymeneely** [comment]
Oh no! That is definitely not the case. The noise tracker tracks noise, and that's it. And multiple things cause alerts: noise, some actions (e.g. Detonate), and Events.

I *could* blame a stupid regression in one of Squib's dependencies where the made a major change in in a patch-level update that has caused chaos on Linux-based systems and therefore broke my travis builds, made some new Squibbers mad/confused, and disenfranchised me from keeping my builds up to date so that any unsuspecting playtester actually sees an older version of things and gets confused. I *could* blame them. But I won't. *cough* I really should just have kept the rules up-to-date like a good boy.

**Comment by andymeneely** [comment]
Alright so even in the master rules I found some bad writing here and there, so v0.16 is even better!
